<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<Title>ABC Shared Library</Title>
		<PackageId>ABCShared.Library</PackageId>
		<Version>1.0.0</Version>
		<Authors>Junior Matlou</Authors>
		<Company>Cloud Toys Pty Ltd</Company>
		<Description>This package include common  resources that can be shared between back-end and front-end apps</Description>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<PackageProjectUrl>https://cloudtoys.com/packages</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageTags>abcschool;shared;dtos</PackageTags>
		<RepositoryUrl>https://github.com/Joshua030/.net_basics</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

</Project>
