//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvidersDemoApp
{


    public partial class Default
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// LoginView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LoginView LoginView1;

        /// <summary>
        /// RolesPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel RolesPanel;

        /// <summary>
        /// LitUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal LitUser;

        /// <summary>
        /// LitRoles control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal LitRoles;

        /// <summary>
        /// DdlRoles control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList DdlRoles;

        /// <summary>
        /// BtnAdd control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnAdd;

        /// <summary>
        /// BtnRemove control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnRemove;
    }
}
